#!/bin/bash

# Stream one tab-separated sample at the requested interval. Keeping one
# collector alive avoids launching a shell and several awk processes for every
# refresh while retaining the widget's original two-second cadence.

interval="${1:-2}"
[[ $interval =~ ^[0-9]+$ ]] && (( interval >= 1 && interval <= 60 )) || interval=2

trap 'exit 0' TERM INT HUP

while true; do
  read -r -a cpu_fields < /proc/stat || exit 1

  cpu_idle=${cpu_fields[4]:-0}
  cpu_total=0
  for ((i = 1; i < ${#cpu_fields[@]}; i++)); do
    ((cpu_total += cpu_fields[i]))
  done

  mem_total_kib=0
  mem_available_kib=0
  while read -r key value _; do
    case "$key" in
      MemTotal:) mem_total_kib=$value ;;
      MemAvailable:) mem_available_kib=$value ;;
    esac
  done < /proc/meminfo

  read -r load_average _ < /proc/loadavg

  printf 'sample\t%s\t%s\t%s\t%s\t%s\n' \
    "$cpu_idle" "$cpu_total" "$mem_available_kib" "$mem_total_kib" "$load_average"

  sleep "$interval" || exit 0
done
